#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: danielkmalungu

This Exploratory Analysis is of the COVID-19 Open Research Dataset.
In response to the COVID-19 pandemic, the White House and a coalition 
of leading research groups have prepared the COVID-19 Open Research 
Dataset (CORD-19). CORD-19 is a resource of over 29,000 scholarly articles,
including over 13,000 with full text, about COVID-19, SARS-CoV-2, and related coronaviruses. 
This freely available dataset is provided to the global research community 
to apply recent advances in natural language processing and other 
AI techniques to generate new insights in support of the ongoing fight against this infectious disease. 
There is a growing urgency for these approaches because of the rapid acceleration in new coronavirus literature, 
making it difficult for the medical research community to keep up.

The link to the dataset:
    https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge
"""

# Importing Core Libraries 
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
import glob
import json
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

# Importing Dataset 
# MetaData
logging.info('Importing MetaData Files')
root_file='/home/danielkmalungu/Documents/Project Startup/COVID-19/CORD-19-research-challenge/2020-03-13/' # The path to the location of the dataset downloaded 
meta_path= root_file+'all_sources_metadata_2020-03-13.csv'
metadataset=pd.read_csv(meta_path)

# JSON Files
logging.info('Importing JSON Files')
all_json=glob.glob(root_file+'/*/*/*.json') #  Allow to search all the file and directories for the file extension provided
print(len(all_json))

# Checking Json Schme Structure
with open(all_json[0]) as file:
    first_entry = json.load(file)
    print(json.dumps(first_entry,indent=4))